# Generated by Django 3.2.18 on 2023-03-08 17:26

from django.db import migrations, models
import passthrough.operations


class Migration(migrations.Migration):

    dependencies = [
        ("django_saml2_auth", "0002_auto_20230308_1725"),
    ]

    operations = [
        passthrough.operations.LockTimeout(),
        migrations.AlterField(
            model_name="samlmetadata",
            name="enable_optional_saml",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="samlmetadata",
            name="enable_saml",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
