# Generated by Django 3.2.18 on 2023-03-14 22:35

from django.db import migrations, models
import passthrough.operations


class Migration(migrations.Migration):

    dependencies = [
        ("django_saml2_auth", "0003_auto_20230308_1726"),
    ]

    operations = [
        passthrough.operations.LockTimeout(),
        migrations.AlterField(
            model_name="samlmetadata",
            name="enable_optional_saml",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="when False, SAML is forced if it is enabled. When True, SAML is optional when it is enabled.",
                null=True,
            ),
        ),
    ]
