name: test

on: push

jobs:
  test:
    name: Test django-saml2-auth
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.5', '3.6', '3.7', '3.8', '3.9', '3.10' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install xmlsec1
        run: sudo apt-get install xmlsec1
      - name: Install dependencies
        run: pip install -r requirements_test.txt && pip install -e .
      - name: Test
        run: pytest .
