name: test

on: push

jobs:
  test:
    name: Test django-saml2-auth
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9', '3.10' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install xmlsec1
        run: sudo apt-get install xmlsec1
      - name: Install dependencies
        run: pip install -r requirements_test.txt && pip install -e .
      - name: Install Django 2.2.27
        run: pip install Django==2.2.27
      - name: Test Django 2.2.27
        run: pytest .
      - name: Install Django 3.2.12
        run: pip install Django==3.2.12
      - name: Test Django 3.2.12
        run: pytest .
      - name: Install Django 4.0.3
        run: pip install Django==4.0.3
      - name: Test Django 4.0.3
        run: pytest .
